name: "Test Scripts"

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  runTests:
    name: "Test Scripts"
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: 'head'

      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: 'base'

      - name: Cache Python venv
        uses: actions/cache@v2
        with:
          path: venv
          key: ${{ runner.os }}-build-${{ hashFiles('head/scripts/requirements.txt') }}

      - name: "Print hashes"
        run: |
          echo "${{ hashFiles('head/scripts') }}"
          echo "${{ hashFiles('base/scripts') }}"

      - name: "Run tests"
        if: ${{ hashFiles('head/scripts') != hashFiles('base/scripts') }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r head/scripts/requirements.txt
          cd head/scripts
          python -m unittest test.common_test