name: "Validate Issuers File Periodically"

on:
  schedule:
    - cron:  '*/60 */4 * * *'

jobs:
  runTests:
    name: "Validate Issuers File"
    runs-on: [ubuntu-latest]
    steps:
      - uses: "actions/checkout@v2"
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Cache Python venv
        uses: actions/cache@v2
        with:
          path: scripts/venv
          key: ${{ runner.os }}-build-${{ hashFiles('**/requirements.txt') }}

      - name: "Validate Issuers File"
        run: |
          cd scripts
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python validate_entries.py ../vci-issuers.json